# Two.rb
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# Process
# Catapillar through fibonacci sequence with two variables
#
# O(n), where n is UPPER_BOUND

UPPER_BOUND = 4000000
behind = 0
ahead  = 1
sum    = 0
while ahead < UPPER_BOUND
	temp   = ahead
	ahead  = ahead + behind
  behind = temp
	sum   += ahead if ahead.even?
end
puts sum
